---
- name: Common
  hosts: all
  become: true

  vars_files:
    - ./devenv_vars.default.yml
    - ./devenv_vars.config.yml
  
  roles:
    - { role: geerlingguy.repo-epel }
    - { role: classyllama.syseng-access }
  
  tasks:
    - package:
        name: "{{ item }}"
      with_items:
        - wget
        - bc
        - rsync
        - lsof
        - ack
        - perl
        - man
        - bash-completion
        - pv
        - git
        - tree
        - ack
        - ps_mem
        - yara
        - patch
        - jq
