---
- name: Common
  hosts: all
  become: true

  vars_files:
    - ./devenv_vars.default.yml
    - ./devenv_vars.config.yml
  
  roles:
    - { role: classyllama.syseng-access }
    - { role: geerlingguy.repo-epel }
    - { role: classyllama.repo_ius, when: use_classyllama_repo_ius | default(false) }
    - { role: classyllama.nvm }
  
  tasks:
    - name: Common Software Packages
      package:
        name: 
          - wget
          - bc
          - rsync
          - yara
          - unzip
          - words
          - coreutils
    
    # EL7 Packages
    - name: Software Packages (EL7)
      package:
        name: 
          - yum-plugin-replace
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version <= '7'
        - use_classyllama_repo_ius == true

    - name: Additional Diagnostics Tools
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nmap-ncat
        - nmap

    # - name: Disable SELinux enforcement
    #   selinux:
    #     state: disabled
    
    # Yum update and reboot as needed
    - name: upgrade all packages
      package:
        name: '*'
        state: latest
      tags: yum-update
    
    - name: check for reboot hint
      shell: if [ $(rpm -q --last kernel | awk 'NR==1 {print $1}') != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'Kernel is current'; fi
      ignore_errors: true
      changed_when: false
      register: reboot_hint
      tags: yum-update
    
    - name: Rebooting ...
      shell: sleep 5 && shutdown -r now 'Rebooting (Yum Updates)'
      async: 1
      poll: 0
      ignore_errors: true
      changed_when: "reboot_hint.stdout == 'reboot'"
      register: rebooting
      tags: yum-update
      when: "reboot_hint.stdout == 'reboot'"

    - name: Wait for remote system to reboot...
      become: no
      wait_for_connection:
        delay: 60
      when: rebooting is changed
      tags: yum-update
