---
- hosts: all
  name: Copy composer credentials for repo.magento.com from host to devenv
  become: yes

  vars_files:
    - ./devenv_vars.default.yml
    - ./devenv_vars.config.yml
  
  tasks:
    
    - name: Create /home/www-data/.ansible/tmp
      file:
        path: /home/www-data/.ansible/tmp
        state: directory
        owner: www-data
        group: www-data
        mode: 0770
    
    - name: Get remote composer user
      shell: /usr/local/bin/composer config -g http-basic.repo.magento.com | jq -r '.username'
      become: yes
      become_user: www-data
      register: remote_user
      changed_when: False
    
    - name: Get remote composer password
      shell: /usr/local/bin/composer config -g http-basic.repo.magento.com | jq -r '.password'
      become: yes
      become_user: www-data
      register: remote_pass
      changed_when: False
    
    - name: Get local composer user
      shell: composer config -g http-basic.repo.magento.com | jq -r '.username'
      become: no
      delegate_to: localhost
      register: local_user
      when: remote_user and remote_user.stdout is defined and remote_user.stdout == ""
    
    - name: Get local composer password
      shell: composer config -g http-basic.repo.magento.com | jq -r '.password'
      become: no
      delegate_to: localhost
      register: local_pass
      when: remote_user and remote_user.stdout is defined and remote_user.stdout == ""
    
    - name: Initialize Composer Magento Repo Auth
      shell: /usr/local/bin/composer config -g http-basic.repo.magento.com {{ local_user.stdout }} {{ local_pass.stdout }}
      become: yes
      become_user: www-data
      when: 
        - remote_user and remote_user.stdout is defined and remote_user.stdout == ""
        - local_user and local_user.stdout is defined and local_user.stdout != ""
        - local_pass and local_pass.stdout is defined and local_pass.stdout != ""
