---
- hosts: all
  name: Dev Env Setup
  become: yes
  
  vars:

  tasks:
    - name: Add www-data to cladmin group
      user:
        name: www-data
        groups: cladmin
        append: yes

    - name: Create projects directory for codebase roots
      file:
        path: /var/www/html/projects
        state: directory
        owner: www-data
        group: www-data
        mode: '775'
