---
# Install Collections and Roles with Ansible Galaxy
# ansible-galaxy role install -r requirements.yml
# ansible-galaxy collection install -r requirements.yml -p ./

# collections:
  
  
roles:
  - src: git@github.com:alpacaglue/ansible-role-composer.git
    name: alpacaglue.composer
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-n98-magerun.git
    name: alpacaglue.n98-magerun
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-php-cachetool.git
    name: alpacaglue.php-cachetool
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-varnish.git
    name: alpacaglue.varnish
    scm: git

  - src: geerlingguy.repo-epel




  - src: git@github.com:classyllama/ansible-role-nginx.git
    name: classyllama.nginx
    scm: git

  - src: git@github.com:classyllama/ansible-role-multi-redis.git
    name: classyllama.multi_redis
    scm: git

  - src: git@github.com:classyllama/ansible-role-repo-ius.git
    name: classyllama.repo_ius
    scm: git

  - src: git@github.com:classyllama/ansible-role-php-fpm.git  
    name: classyllama.php_fpm
    scm: git
    version: feature/ansible-29

  - src: git@github.com:classyllama/ansible-role-nginx.git
    name: classyllama.nginx
    scm: git
    version: feature/ansible-29






  - src: git@github.com:alpacaglue/ansible-role-devops-access.git
    name: alpacaglue.devops-access
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-boilerplate.git
    name: alpacaglue.boilerplate
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-www-user.git
    name: alpacaglue.www-user
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-hostsfile.git
    name: alpacaglue.hostsfile
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-repo-percona.git
    name: alpacaglue.repo-percona
    scm: git

  - src: git@github.com:alpacaglue/ansible-role-percona.git
    name: alpacaglue.percona
    scm: git
