---
# Install Collections and Roles with Ansible Galaxy
# ansible-galaxy role install -r requirements.yml
# ansible-galaxy collection install -r requirements.yml -p ./

# collections:
  
  
roles:

  # - src: git@github.com:classyllama/ansible-role-boilerplate.git
  #   name: classyllama.boilerplate
  #   # testing RHEL/CentOS 8 Support
  #   version: el8-support
  #   scm: git
  
  - src: git@github.com:classyllama/ansible-role-composer.git
    name: classyllama.composer
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-dbbackup.git
    name: classyllama.dbbackup
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-filebackup.git
    name: classyllama.filebackup
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-hostsfile.git
    name: classyllama.hostsfile
    scm: git

  - src: git@github.com:classyllama/ansible-role-magento-logrotate.git
    name: classyllama.magento-logrotate
    scm: git
  
  # - src: xxxxxxxxxxxxxxxxx
  #   name: classyllama.mariadb
  #   scm: git
  
  - src: git@github.com:classyllama/ansible-role-multi-redis.git
    name: classyllama.multi_redis
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-n98-magerun.git
    name: classyllama.n98-magerun
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-nginx.git
    name: classyllama.nginx
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-percona.git
    name: classyllama.percona
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-php-fpm.git  
    name: classyllama.php_fpm
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-php-cachetool.git
    name: classyllama.php-cachetool
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-rclone.git
    name: classyllama.rclone
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-rclone-archiver.git
    name: classyllama.rclone-archiver
    scm: git
  
  - src: git@github.com:classyllama/ansible-role-repo-ius.git
    name: classyllama.repo_ius
    scm: git
  
  # - src: xxxxxxxxxxxxxxxxx
  #   name: classyllama.repo-nginx
  #   scm: git
  
  # - src: xxxxxxxxxxxxxxxxx
  #   name: classyllama.repo-nginx-appstream
  #   scm: git
  
  - src: git@github.com:classyllama/ansible-role-repo-percona.git
    name: classyllama.repo-percona
    scm: git
  
  # - src: xxxxxxxxxxxxxxxxx
  #   name: classyllama.repo-php-appstream
  #   scm: git
  
  # - src: xxxxxxxxxxxxxxxxx
  #   name: classyllama.repo-python3-appstream
  #   scm: git
  
  # - src: xxxxxxxxxxxxxxxxx
  #   name: classyllama.repo-varnish
  #   scm: git
  
  - src: git@github.com:classyllama/ansible-role-syseng-access.git
    name: classyllama.syseng-access
    scm: git
  
  # - src: git@github.com:classyllama/ansible-role-varnish.git
  #   name: classyllama.varnish
  #   scm: git
  
  - src: git@github.com:classyllama/ansible-role-www-user.git
    name: classyllama.www-user
    scm: git









  # 3rd Party Ansible Roles
  - src: git@github.com:elastic/ansible-elasticsearch.git
    version: 25bd09f # last version to support multi-environment install
    name: elastic.elasticsearch
    scm: git

  - src: geerlingguy.repo-epel
  
  - src: geerlingguy.repo-remi
