---
- name: Common
  hosts: all
  become: true

  vars_files:
    - ./devenv_vars.default.yml
    - ./devenv_vars.config.yml
  
  tasks:
    - parted:
        device: /dev/sdb
        number: 1
        state: present

    - filesystem:
        fstype: xfs
        dev: /dev/sdb1

    - mount:
        path: /data
        src: /dev/sdb1
        fstype: xfs
        opts: defaults,nofail,discard
        state: mounted
